config: add `azurestackhci` @ `2022-09-01`
hashicorp/pandora pull request #1616
Opened 2022-09-30 06:07 UTC by liuwuliuyun

swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2022-09-01
doc: https://learn.microsoft.com/en-us/azure-stack/hci/

2022-10-06 04:00 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/pandora?pullRequest=1616)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/pandora?pullRequest=1616)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/pandora?pullRequest=1616).</sub>

2022-10-13 03:07 UTC, katbyte commented
@liuwuliuyun  - as this was forked and opened before the repo went public and the GHA's functioned correctly - you'll need to re-fork the repo and open a new PR with this change for them to property trigger. Thanks!

2022-10-13 03:19 UTC, katbyte requested changes
see above comment

2022-10-13 05:43 UTC, liuwuliuyun commented
Got it, let me retry this one.

2022-10-13 05:43 UTC, closed without merging