`importer`:  use `RawFile` instead of `object` for request as object type but format with file
hashicorp/pandora pull request #2332
Opened 2023-04-06 07:51 UTC by wuxu92

try to resolve: #2185 

imported cs file:

![image](https://user-images.githubusercontent.com/2633022/230310505-d8cec20c-3aef-4fcd-b9d5-891d496ee67f.png)

2023-04-06 08:35 UTC, tombuildsstuff requested changes
hey @wuxu92 

Thanks for this PR - I've taken a look through and left some comments inline, if we can fix those up then this should otherwise be good to go 👍 

Thanks!

2023-04-06 08:35 UTC, tombuildsstuff commented on tools/importer-rest-api-specs/components/parser/models.go
> +	if input.Type.Contains("file") || (input.Format == "file" && input.Type.Contains("object")) {
we need this to be case-insensitive due to inconsistencies in the Swagger

```suggestion
	if input.Type.Contains("file") || (strings.EqualsFold(input.Format, "file") && input.Type.Contains("object")) {
```

2023-04-06 08:35 UTC, tombuildsstuff commented on tools/importer-rest-api-specs/components/parser/testdata/model_single_with_rawfile.json
> +              "$ref": "#/definitions/Example"
we should update the Response to return a file too, so that we can verify (in the test above) that we parse this out in both directions

2023-04-06 08:35 UTC, tombuildsstuff commented on tools/importer-rest-api-specs/components/parser/models.go
>  		return &models.ObjectDefinition{
thinking about it, it'd make more sense to move this logic here, leaving the change above as-is and making this:

```suggestion
		if strings.EqualsFold(input.Format, "file") {
			return &models.ObjectDefinition{
				Type: models.ObjectDefinitionRawFile,
			}
		}
		return &models.ObjectDefinition{
```

2023-04-06 09:51 UTC, tombuildsstuff requested changes
hey @wuxu92 

Thanks for pushing those changes, I've taken a look through and left another couple of minor comments inline, but it appears that some of the comments from last time were missed?

Thanks!

2023-04-07 02:14 UTC, wuxu92 commented
> 

thanks for your comments, sorry i did not get all your points in the last push 🔆

2023-05-03 08:47 UTC, tombuildsstuff approved these changes
LGTM - thanks for pushing those changes @wuxu92

2023-05-03 08:52 UTC, merged