WIP `tools/terraform-generator`: fix issues in loadTestService
hashicorp/pandora pull request #2497
Opened 2023-05-10 06:19 UTC by wuxu92

1. should not set schema if sdk model field is nil. resolves #2483
2. add model2model mappings of nestItems. or generated resource will missing mapXXX functions.

base on #2072. will be ready to merge once #2072 merged.

2023-05-17 00:58 UTC, tombuildsstuff requested changes
hey @wuxu92 

Thanks for this PR.

I've taken a look through and unfortunately this PR's going in quite a different direction to where we're intending to take the Terraform generator - so I'm not sure we're going to be able to proceed with this PR in it's current state.

Namely, we're intentionally avoiding adding workarounds within the codebase in favour of fixing the source data (aside from where it's expected that a PR will be merged in the short-term/to unblock us).

It's worth also calling out that a key design decision of Pandora is that all of the generated files can be removed at any time - and re-run (which is how the Terraform Generator works today) - so unfortunately allowing changes to the auto-generated files isn't something we can ship - since this'd lead to workarounds atop workarounds, which ultimately cause more issues long-term.

As you've identified, the root-cause of the issue with the Load Test Service resource is that the `identity` field is duplicated within one of the nested blocks, but is being top-levelled anyway and overwriting the original value. As such instead of taking the approaches outlined in this PR, I think this'd be best handled as a model processor - since we can validate that the field doesn't exist within the parent resource, and work from there (and validate that if it does, we're _intentionally_ ignoring/renaming the field for now).

Given the number of changes needed within this PR and that we're going to need to take a fundamentally different approach here - whilst I'd like to thank you for this contribution, I'm going to close this PR for the moment - but we'll take a look into the root-cause of this one in the not-too-distant future, since we're aware that we need to move off of this older API Version.

Thanks!

2023-05-17 03:11 UTC, wuxu92 commented on tools/generator-terraform/generator/resource/resource.go
> +}
thanks. it looks reasonable to not skip specific files.

2023-05-17 03:23 UTC, wuxu92 commented on tools/importer-rest-api-specs/components/testattributes/test_dependency.go
> +}
for most of resources, the dependencies is complex and diferent from one to others. an example as when both resource A and B dependent on a `azurerm_key_vault_key` resource, they may need a different  configuraiton of the `azurerm_key_vault` resource to create the `key` resource (this is what LoadTestService required). is there a simple way to handle it?

2023-06-08 17:35 UTC, tombuildsstuff commented
hey @wuxu92 

Thanks for pushing the changes to this PR - apologies for the delayed re-review here.

As mentioned in https://github.com/hashicorp/pandora/pull/2576, we've ended up reworking some of the internals about how the Terraform Resource Schema, Mappings and Test Generation works such that this PR has been superseded.

At this point in time we've looked to implement this in a slightly different manner, temporarily removing the `encryption` block (since there's a number of changes needed to support this) - which are being tracked in https://github.com/hashicorp/pandora/issues/2608 - and as such the Load Test resource has been updated to the latest API version as of https://github.com/hashicorp/pandora/pull/2609.

Since that's currently working it's way through into the Terraform Provider, since this PR was primarily to unlock the Load Test Service, whilst I'd like to thank you for this contribution I'm going to close this PR for the moment - however the remaining issues needed to pipe this additional field through are being tracked in #2608.

Thanks!

2023-06-08 17:35 UTC, closed without merging