Data API V2: extending `NewServicesRepository` to build a complete list of services
hashicorp/pandora pull request #3392
Opened 2023-11-22 08:07 UTC by stephybun

Closes #3277

**Summary:**
- `NewServicesRepository` has been updated to do the following:
    - Auto discovers subdirectories in the root dir of the api definitions with a `metadata.json`
    - Checks the DataSource specified in the `metadata.json` and builds a complete list of services for a given service type that populates the new attribute `serviceDirectory` which maps the service to a filepath
    - Validates that there aren't duplicate definitions for a service across several directories
    - Returns errors

- Updated the paths we use when loading the definitions to use the information stored in the new attribute `serviceDirectory`
- The entry point into the server/root routing handles the error for `NewServicesRepository` and exits if there is one
- `ServiceDefinition.json` is being loaded and processed now

TODO in a separate PR:
- Logging should be threaded through properly using whatever logging mechanism that chi relies on

2023-11-22 17:00 UTC, tombuildsstuff requested changes
On the whole this is looking good, but we should commit to either fixing or removing the cache, which (as discussed offline) I'll open an issue to track - however if the other comments can be addressed then this should otherwise be good to go 👍

2023-11-27 13:32 UTC, tombuildsstuff commented on tools/data-api/internal/repositories/services.go
> +	if _, err := os.Stat(s.serviceDirectory[serviceName]); os.IsNotExist(err) {
Opened https://github.com/hashicorp/pandora/issues/3411 to track this

2023-11-28 10:11 UTC, tombuildsstuff approved these changes
Aside from a handful of minor nits for consistency/styling this otherwise LGTM 👍

2023-11-28 10:55 UTC, stephybun commented on tools/data-api/internal/repositories/services.go
> +	resourcePath := path.Join((*s.serviceNamesToDirectory)[serviceName], version, resource)
`servicePath` is defined in `ProcessServiceDefinitions` where it's used multiple times.

This is a `ProcessResourceDefinitions` and it's only used once so I'm going to keep it as is.

2023-11-28 10:55 UTC, stephybun commented on tools/data-api/internal/repositories/services.go
> +	terraformDefinitionsPath := path.Join((*s.serviceNamesToDirectory)[serviceName], "Terraform")
ditto

2023-11-28 11:14 UTC, merged