`tools/importer-rest-api-specs`: removing the logic for outputting V1 of the API Definitions
hashicorp/pandora pull request #3633
Opened 2024-01-17 10:40 UTC by tombuildsstuff

This PR removes the logic which output the V1 API Definitions - and also removes the feature toggle for V2, since this is now defaulted on.

I've also updated the README to account for the changes - and called out the paths which will be removed in the near future.

2024-01-19 09:32 UTC, stephybun requested changes
Thanks @tombuildsstuff. Looks mostly fine, a few minor renames are missing. Can we also remove the steps where we build the legacy Data API in this GHA
https://github.com/hashicorp/pandora/blob/8a17f3073483253f71007d0350ab920ce7fd66e3/.github/workflows/automation-regenerate-terraform.yaml#L27-L35

2024-01-19 09:32 UTC, stephybun commented on tools/importer-rest-api-specs/pipeline/run_importer.go
> +			fmt.Errorf("recreating JSON directory %q for service %q", serviceDirectoryV2, serviceName)
```suggestion
		serviceDirectory := path.Join(input.OutputDirectory, serviceName)
		logger.Debug("recreating the working directory at %q for Service %q", serviceDirectory, serviceName)
		if err := dataapigeneratorjson.RecreateDirectory(serviceDirectory, logger); err != nil {
			fmt.Errorf("recreating directory %q for service %q", serviceDirectory, serviceName)
```

2024-01-19 09:32 UTC, stephybun commented on tools/importer-rest-api-specs/pipeline/task_generate_data_api_definitions_v2.go
Rename this file: `task_generate_data_api_definitions_v2.go` -> `task_generate_data_api_definitions.go`

2024-01-19 09:32 UTC, stephybun commented on tools/importer-rest-api-specs/pipeline/task_output_metadata.go
> +		return fmt.Errorf("outputting the Revision ID into the V2 Data: %+v", err)
```suggestion
		return fmt.Errorf("outputting the Revision ID: %+v", err)
```

2024-01-22 06:55 UTC, stephybun approved these changes
There's still a GHA step that I think can be removed, otherwise LGTM 👍

2024-01-22 06:55 UTC, stephybun commented on .github/workflows/automation-regenerate-terraform.yaml
>            dotnet-version: 7.0.x
Shouldn't need this step anymore either?

2024-01-23 10:05 UTC, tombuildsstuff commented
The Graph failure is unrelated / fine to skip for now.

2024-01-23 10:05 UTC, merged